name: Build 100x 🚀

on:
    pull_request:
        branches: [main]
    push:
        branches: [main]
    workflow_dispatch:

permissions: read-all

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
    lint-code:
        name: ✨ Lint code (Pre-commit)
        runs-on: ubuntu-latest
        timeout-minutes: 5
        steps:
            - name: Checkout Code
              uses: actions/checkout@v5
            - name: Run pre-commit
              uses: pre-commit/action@v3.0.1

    test-python:
        name: 🐍 Test Python backend
        runs-on: ubuntu-latest
        timeout-minutes: 5

        steps:
            - name: Checkout Code
              uses: actions/checkout@v5
            - name: Setup Python
              uses: actions/setup-python@v6
              with:
                  python-version: "3.13"
            - name: Install uv with cache
              uses: astral-sh/setup-uv@v6
              with:
                  enable-cache: true
                  cache-dependency-glob: |
                      requirements/requirements.in
                      requirements/requirements.txt
                      requirements/requirements-test.txt
            - name: Install dependencies with uv
              run: |
                  uv pip install --system -r requirements/requirements-test.txt
            - name: Run the tests with coverage
              run: pytest -n 3 --cov=./ --cov-report=xml
            - name: Upload coverage to Codecov
              uses: codecov/codecov-action@v5
              with:
                  token: ${{ secrets.CODECOV_TOKEN }}
                  files: ./coverage.xml
